### ISSUE TITLE
BUG: Cannot export Android model:

### ISSUE THREAD

**Issue by MusaMahmood** [MusaMahmood/SSVEP-Deep-Learning#13]
```
Traceback (most recent call last):
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2017.2.3\helpers\pydev\pydevd.py", line 1599, in <module>
    globals = debugger.run(setup['file'], None, None, is_module)
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2017.2.3\helpers\pydev\pydevd.py", line 1026, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2017.2.3\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "C:/Users/Musa Mahmood/Dropbox (GaTech)/YeoLab/Deep Learning/SSVEP-Deep-Learning/Tensorflow/CNN_basic_mamem.py", line 325, in <module>
    main()
  File "C:/Users/Musa Mahmood/Dropbox (GaTech)/YeoLab/Deep Learning/SSVEP-Deep-Learning/Tensorflow/CNN_basic_mamem.py", line 318, in main
    export_model([input_node_name, keep_prob_node_name], output_node_name)
  File "C:/Users/Musa Mahmood/Dropbox (GaTech)/YeoLab/Deep Learning/SSVEP-Deep-Learning/Tensorflow/CNN_basic_mamem.py", line 283, in export_model
    "save/Const:0", EXPORT_DIRECTORY + '/frozen_' + MODEL_NAME + '.pb', True, "")
  File "F:\Anaconda3\lib\site-packages\tensorflow\python\tools\freeze_graph.py", line 184, in freeze_graph
    variable_names_blacklist)
  File "F:\Anaconda3\lib\site-packages\tensorflow\python\tools\freeze_graph.py", line 84, in freeze_graph_with_def_protos
    for node in input_graph_def.node:
AttributeError: 'int' object has no attribute 'node'
```

**Comment by MusaMahmood** [comment]
Fixed. The missing pbtxt must be present.
